wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1679370999.379168
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.13.7
      8:
      - 5
act:
  desc: null
  value: ReLU
batch:
  desc: null
  value: 64
clf:
  desc: null
  value: skl_logress
dataset:
  desc: null
  value: politifact
device:
  desc: null
  value: cuda:2
dropout:
  desc: null
  value: 0.8
fuse:
  desc: null
  value: concat
k:
  desc: null
  value: 2
llm:
  desc: null
  value: clip
lvm:
  desc: null
  value: clip
output_dim:
  desc: null
  value: 256
root_path:
  desc: null
  value: /data/dahn017/KDD23
